name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool: myAgent012022
    steps:
    - task: CmdLine@2
      displayName: Install Newman Runner
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Run Newman Test
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: 'starter-code/automatedtesting/postman'
    
    